# Cau hinh ket noi SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bt2_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cau hinh Gui Email qua Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ang020106@gmail.com
spring.mail.password=xxxx xxxx xxxx xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true